### ISSUE TITLE
Flash messages are not cleared when changing page

### ISSUE THREAD

**Issue by jstockwin** [jakestockwin-co-uk/robin-thompson#1]
This is probably due to the way we do page changes. However given the error pops up correctly, there must be a way to close it too. 

To reproduce, simply navigate to `host:port/research/blah`. An error is correctly thrown, because `blah` is not a project. However now when clicking other links, this error will never go away.

**Comment by unpairedbracket** [comment]
Fixed as of 4b1577657f1eaedaa4b2ccefeaffa8906b80f272
